name: telegram message
on: [push]
 
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: appleboy/telegram-action@master
      with:
        to: ${{1416774366 }}
        token: ${{1241794088:AAEV0YsfuYZzR4OwD2OAuub3bvTcyejUT-Y }}
   
